stages:
  - package
  - build

package:
  stage: package
  script:
    - docker-compose down
    - docker build -t itcast/front-pyg-service service
    - docker build -t itcast/front-pyg-application application
  tags:
    - centos-137

build:
  stage: build
  script:
   - docker-compose up -d
  tags:
   - centos-137
