version: '3.3'

services:
  mysql:
    image: mysql:5.7
    restart: always
    command: mysqld  --skip-ssl --character_set_server=utf8mb4 --sql_mode=""
    volumes:
      - ./data:/docker-entrypoint-initdb.d/
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    # ports:
    #   - 3306:3306
  service:
    image: itcast/front-pyg-service
    restart: always
    depends_on:
      - mysql
    environment:
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASS=
      - DB_NAME=newshop
    ports:
      - 8100:80
  application:
    image: itcast/front-pyg-application
    restart: always
    # ports:
    #   - 8100:3080
    depends_on:
      - service
    environment:
      - API_BASE=http://service:2080/v1
      - NODE_ENV=production
